FROM ros:noetic

LABEL maintainer "Ragesh Ramachandran <ragesh.ramachandran@ipa.fraunhofer.de>"
SHELL ["/bin/bash","-c"]

RUN apt-get update && apt-get -y upgrade 

RUN apt-get install -y git \
	&& apt-get -y install python3-pip \
	&& apt-get update && apt-get -y upgrade 

ENV CATKIN_WS=/root/catkin_ws
RUN mkdir -p $CATKIN_WS/src
WORKDIR $CATKIN_WS/src

RUN git clone https://github.com/ipa-rar/THMHO_heatmap_launcher.git
RUN git clone -b intel_nuc https://github.com/ipa-rar/THMHO_heatmap_generator.git

WORKDIR $CATKIN_WS
RUN echo "Pulling & Compiling THMHO module" \
	&& source /opt/ros/noetic/setup.bash \
	&& rosdep install --from-paths src --ignore-src -r -y \
	&& catkin_make \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /entrypoint.sh" >> /root/.bashrc

COPY ./docker/entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]